### ISSUE TITLE
Feature Suggestion: Tweening library

### ISSUE THREAD

**Issue by lizenas** [thebeardphantom/UnityCommonLibrary#1]
An MIT-licensed tweening library taking inspiration from [ZestKit](https://github.com/prime31/ZestKit) and/or [DOTween](http://dotween.demigiant.com/), which both have excellent features, but vastly less permissive licenses would be amazing.

**Comment by thebeardphantom** [comment]
I don't think the time investment into a tweening library that can perform as well as DOTween would be worthwhile. DOTween is highly performant, so matching it would be a long endeavor. I tend to break off large systems from UCL if they get too big and are worthy of a separate project altogether, which is what would happen to a tweening library that could compete.
